"""add is_admin to users

Revision ID: 02df91d655e9
Revises: dfb2906cd7b8
Create Date: 2023-05-13 19:53:22.886325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02df91d655e9'
down_revision = 'dfb2906cd7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.execute("UPDATE users SET is_admin = (email = 'mrkaye97@gmail.com')")
        batch_op.alter_column('is_admin', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
