"""Adds last_received_email_at

Revision ID: 0b58115f817b
Revises: 8f41994ef2f5
Create Date: 2023-05-30 20:55:39.163446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b58115f817b"
down_revision = "8f41994ef2f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_received_email_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_received_email_at")

    # ### end Alembic commands ###
