"""Add dead link flag

Revision ID: 504bffd294d8
Revises: 9b7b65683177
Create Date: 2023-06-01 19:36:33.344206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504bffd294d8'
down_revision = '9b7b65683177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_url_is_dead_link', sa.Boolean(), nullable=True))

    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.execute("UPDATE companies SET board_url_is_dead_link = False")
        batch_op.alter_column("board_url_is_dead_link", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('board_url_is_dead_link')

    # ### end Alembic commands ###
