"""expand link columns:


Revision ID: 5e3c5f0e7bad
Revises: eca6aeecd6b3
Create Date: 2023-04-27 21:26:19.057414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e3c5f0e7bad"
down_revision = "eca6aeecd6b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.alter_column(
            "link_text",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.String(length=2048),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "link_href",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.String(length=2048),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.alter_column(
            "link_href",
            existing_type=sa.String(length=2048),
            type_=sa.VARCHAR(length=256),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "link_text",
            existing_type=sa.String(length=2048),
            type_=sa.VARCHAR(length=256),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
