"""Adds url prefix to company

Revision ID: 78583647fe23
Revises: df110c955394
Create Date: 2023-04-23 00:09:59.779857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78583647fe23'
down_revision = 'df110c955394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_posting_url_prefix', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('job_posting_url_prefix')

    # ### end Alembic commands ###
