"""add timestamps to postings

Revision ID: 8386665855b8
Revises: 02df91d655e9
Create Date: 2023-05-26 21:53:52.912715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8386665855b8"
down_revision = "02df91d655e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.execute("UPDATE postings SET created_at = NOW()")
        batch_op.alter_column("created_at", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
