"""Adds has_seen_add_company_modal

Revision ID: 8f41994ef2f5
Revises: 8386665855b8
Create Date: 2023-05-28 16:09:13.385660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f41994ef2f5"
down_revision = "8386665855b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_seen_add_company_helper_modal", sa.Boolean(), nullable=True)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.execute("UPDATE users SET has_seen_add_company_helper_modal = False")
        batch_op.alter_column("has_seen_add_company_helper_modal", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("has_seen_add_company_helper_modal")

    # ### end Alembic commands ###
