"""Add postings table to hold links from scraping

Revision ID: 9d74e28e8d80
Revises: 42e716c0ca90
Create Date: 2023-04-21 20:54:44.148020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d74e28e8d80"
down_revision = "42e716c0ca90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("link_text", sa.String(length=256), nullable=True),
        sa.Column("link_href", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_postings_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_postings_link_href"), ["link_href"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_postings_link_text"), ["link_text"], unique=False
        )

    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("posting_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "postings", ["posting_id"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_email")
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index("ix_users_email", ["email"], unique=False)

    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("posting_id")

    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_postings_link_text"))
        batch_op.drop_index(batch_op.f("ix_postings_link_href"))
        batch_op.drop_index(batch_op.f("ix_postings_company_id"))

    op.drop_table("postings")
    # ### end Alembic commands ###
