"""remove unique constraint for board

Revision ID: c7a7a45a668a
Revises: e072bfcfd0ea
Create Date: 2023-04-18 22:35:29.740799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a7a45a668a'
down_revision = 'e072bfcfd0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_constraint('boards_company_url_search_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_unique_constraint('boards_company_url_search_text_key', ['company', 'url', 'search_text'])

    # ### end Alembic commands ###
