"""text -> regex

Revision ID: df110c955394
Revises: 9d74e28e8d80
Create Date: 2023-04-21 21:06:15.454786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df110c955394"
down_revision = "9d74e28e8d80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("search_regex", sa.String(length=256)))
        batch_op.drop_column("search_text")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "search_text",
                sa.VARCHAR(length=256),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("search_regex")

    # ### end Alembic commands ###
