"""FK searches and postings to the company

Revision ID: dfb2906cd7b8
Revises: 1c71d812de2b
Create Date: 2023-05-07 14:10:45.467778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dfb2906cd7b8"
down_revision = "1c71d812de2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.drop_constraint("searches_posting_id_fkey", type_="foreignkey")
        batch_op.drop_column("posting_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("posting_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "searches_posting_id_fkey", "postings", ["posting_id"], ["id"]
        )

    # ### end Alembic commands ###
