"""add default search regex column

Revision ID: eca6aeecd6b3
Revises: 78583647fe23
Create Date: 2023-04-26 21:10:35.601324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eca6aeecd6b3"
down_revision = "78583647fe23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_search_regex", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("default_search_regex")

    # ### end Alembic commands ###
